### ISSUE TITLE
온보딩 화면 퍼블리싱

### ISSUE THREAD

**Issue by kimxwan0319** [team-xquare/xquare-iOS#128]
### Describe

온보딩 화면의 UI를 개발합니다.

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃
