### ISSUE TITLE
탭바 및 네비게이션바 최적화

### ISSUE THREAD

**Issue by kimxwan0319** [team-xquare/xquare-iOS#196]

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

**Comment by xquare-admin** [comment]
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃
