### ISSUE TITLE
학사일정 Bug 수정

### ISSUE THREAD

**Issue by BJCHO0501** [team-xquare/xquare-iOS#443]
### Describe
학사일정 뷰의 버튼이 겹치는 현상과 캘린더가 LazyVStack안에 있어 스크롤할때 끊기는 버그를 고칩니다.
<img width="374" alt="스크린샷 2023-03-27 오후 1 13 37" src="https://user-images.githubusercontent.com/80248855/227839272-b34c5624-c304-4c45-a6ff-446e85cced66.png">
![7fyw0f](https://user-images.githubusercontent.com/80248855/227838786-7689ea2e-63a5-4c2a-ab7d-b318739b1a4f.gif)

**Comment by kimxwan0319** [comment]
어떤 버그인지 이슈 내용에 담아주세요
